### ISSUE TITLE
Slice-Status off markanter darstellen

### ISSUE THREAD

**Issue by Hirbod** [FriendsOfREDAXO/bloecks#21]
Ich finde, dass es noch nicht eindeutig sichtbar genug ist, wenn ein Slice den status off hat. Es müsste deutlicher herausstechen (ggf. opacity .3 oder so).

**Comment by Hirbod** [comment]
Ich hab es mir noch mal angeschaut.
https://github.com/FriendsOfREDAXO/bloecks/blob/master/plugins/status/assets_src/less/be.less#L27

0.7 ist zu viel,  0.3 ist ein super Wert. Jedoch sollte man das nicht auf's ganze `<li>` anwenden.
Damit verhindert man, dass die Statusbar zu sehr in den Hintergrund (und fälschlicherweise als inaktiv getriggerd wird). 

Lieber aufs panel-body.

```css
/* kann bleiben, damit die toolbar zumindest etwas reduzierter wirkt */
.rex-slice-status-off {
    opacity: .7; 
}
/* sollte noch dazu */
.rex-slice-status-off .panel-body {
    opacity: .3;
    pointer-events: none;
}
```

Des Weiteren wäre es super, dann auch auf den deaktivierten panel-body die pointer-events zu verhindern (falls man eine Ausgabe mit Links o.Ä. hat). Das fehlt mir hier noch!
